# game/Cargo.toml - Korrigiert für WASM ohne Module-Fehler
[package]
name = "game"
version = "0.1.0"
edition = "2021"
description = "Fuel Drift - A Rust cave flying game built with Macroquad"
license = "MIT"
repository = "https://github.com/yourusername/fuel-drift"
keywords = ["game", "macroquad", "cave", "flying"]
categories = ["games"]

[[bin]]
name = "fuel-drift"
path = "src/main.rs"

[dependencies]
console_error_panic_hook = "0.1.7"
core = { path = "../core" }
macroquad = { workspace = true }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["Window", "Document", "HtmlElement", "Text"] }

# WASM-spezifische Konfiguration
[target.wasm32-unknown-unknown.dependencies]
wasm-bindgen = { version = "0.2.100", features = ["std"] }

# Optimierungen für WASM
[profile.release]
lto = true
opt-level = "s"  # Optimiert für Größe
codegen-units = 1
panic = "abort"

# Debug-Build für WASM Development
[profile.dev]
panic = "abort"
debug = true
opt-level = 1