# Cargo.toml (Root Workspace)
[workspace]
members = ["core", "game"]
resolver = "2"

[workspace.dependencies]
macroquad = "=0.4"  # Fixe Version

[profile.release]
# WASM-Optimierungen
lto = true
codegen-units = 1
panic = "abort"
