[package]
name = "core"
version = "0.1.0"
edition = "2021"
description = "Core game logic for Fuel Drift - a Rust cave flying game"
license = "MIT"
repository = "https://github.com/yourusername/fuel-drift"
keywords = ["game", "physics", "cave", "flying"]
categories = ["games", "simulation"]

[dependencies]